schema: http                  # support http and https
port: 8089                    # port for balancer
ssl_certificate:
ssl_certificate_key:
tcp_health_check: true
health_check_interval: 3      # health check interval (second)
# The maximum number of requests that the balancer can handle at the same time
# 0 refers to no limit to the maximum number of requests
max_allowed: 100
location:                     # route matching for reverse proxy
  - pattern: /gate/v1/api/product/**
    method: GET
    remove_prefix: true
    proxy_pass:                   # URL of the reverse proxy
      - "http://localhost:8081"
      - "http://localhost:8082"
    balance_mode: round-robin     # load balancing algorithm
  - pattern: /gate/v1/api/consumer/**
    method: GET
    remove_prefix: true
    proxy_pass:                   # URL of the reverse proxy
      - "http://localhost:8081"
      - "http://localhost:8082"
    balance_mode: round-robin     # load balancing algorithm